baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ashot Matevosyan'



copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
enableInlineShortcodes = true

paginate = 10
paginatePath = 'page'

[params]
  color = 'light' # linen, wheat, gray, light

  # twitter = 'ashmat98'
  github = 'ashmat98'
  # instagram = 'nan.xiaobei'
  linkedin = 'ashmat98'             # linkedin.com/in/YOUR_LINKEDIN_ID
  scholar = 't6St-HsAAAAJ'
  avatar = '/profile.jpg'
  name = 'Ashot Matevosyan'
  bio = ' '
  # bio = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply dummy text of the printing and typesetting industry'
  description = "Ashot Matevosyan's homepage"


  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true    # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  
  comments = false                            # disable comments for a specific page

  
[menu]

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 30
  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 20
  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 45


defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.am]
    languageName = "Armenian"
    weight = 2
    title = "Աշոտ Մաթևոսյան"